apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
   app: events-web
 name: events-web
spec:
 replicas: 3
 selector:
   matchLabels:
     app: events-web
     ver: v2.0
 template:
   metadata:
     labels:
       app: events-web
       ver: v2.0
   spec:
     containers:
     - image: vivekchandra/events-website:v2.0
       name: events-web
       ports:
       - containerPort: 8080